language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3
install:
  - pip install pytest coverage coverage-python-version coveralls
  - pip install -e .
script:
  - coverage run -m pytest
  - coverage report
after_success:
  - coveralls
notifications:
  email: false
cache: pip
